public class mavi {
    public Integer sum(Integer x, Integer y){
        
        Integer result =x+y;
        return result;
    }
public Integer sub(Integer x, Integer y){
        
        Integer result =x-y;
        return result;   
}
    public Integer mul(Integer x, Integer y){
        
        Integer result =x*y;
        return result;
    }
    public Decimal div(Decimal x, Decimal y){
        
        Decimal result =x/y;
        return result;
    }
}